package br.psi.giganet.stockapi.config.security;

public enum Permissions {
    ROLE_ADMIN,
    ROLE_ROOT,
    ROLE_PRODUCTS_READ,
    ROLE_PRODUCTS_WRITE,
    ROLE_UNITS_READ,
    ROLE_PURCHASE_ORDERS_READ,

    ROLE_ENTRIES_READ,
    ROLE_ENTRIES_WRITE,
    ROLE_ENTRIES_WRITE_MANUAL,

    ROLE_STOCKS_READ,
    ROLE_STOCKS_WRITE,

    ROLE_PATRIMONIES_READ,
    ROLE_PATRIMONIES_WRITE,
    ROLE_PATRIMONIES_WRITE_ROOT,

    ROLE_PATRIMONIES_LOCATIONS_READ,
    ROLE_PATRIMONIES_LOCATIONS_WRITE,

    ROLE_MOVES_READ,
    ROLE_MOVES_WRITE_ENTRY_ITEMS,
    ROLE_MOVES_WRITE_BETWEEN_STOCKS,
    ROLE_MOVES_WRITE_OUT_ITEM,
    ROLE_MOVES_WRITE_ROOT,
    ROLE_MOVES_SERVICE_ORDER_WRITE,
    ROLE_MOVES_WRITE_BETWEEN_BRANCH_OFFICE,

    ROLE_NOTIFICATIONS,
    ROLE_NOTIFICATIONS_STOCK_ITEM_LOW_LEVEL,
    ROLE_NOTIFICATIONS_STOCK_ITEM_VERY_LOW_LEVEL,

    ROLE_TEMPLATES_READ,
    ROLE_TEMPLATES_WRITE,

    ROLE_BRANCH_OFFICES_READ,
    ROLE_BRANCH_OFFICES_WRITE,

    ROLE_SALES_MODULE;
}
